name: Fast Compile kmod-rkp-ipid

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  compile-kmod-rkp-ipid:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout ImmortalWrt
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: master
        fetch-depth: 1

    - name: Checkout kmod-rkp-ipid
      run: git clone --depth 1 https://github.com/IOEKKO/rkp-ipid.git package/kmod-rkp-ipid && ls -la package/kmod-rkp-ipid/

    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget ninja-build openssl python3-pip libdeflate-tools ccache
        python3 -m pip install meson>=0.64 ninja

    - name: Setup Environment
      run: |
        mkdir -p staging_dir/host/bin
        ln -sf $(which meson) staging_dir/host/bin/meson || true
        ln -sf $(which ninja) staging_dir/host/bin/ninja || true
        ln -sf $(which python3) staging_dir/host/bin/python3 || true

    - name: Create Config
      run: |
        echo "CONFIG_TARGET_mediatek=y" > .config
        echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
        echo "CONFIG_TARGET_mediatek_filogic_DEVICE_generic=y" >> .config
        echo "CONFIG_TARGET_ARCH=aarch64" >> .config
        echo "CONFIG_TARGET_CPU=cortex-a53" >> .config
        echo "CONFIG_PACKAGE_kmod-rkp-ipid=y" >> .config
        echo "CONFIG_PACKAGE_libopenssl=y" >> .config
        echo "CONFIG_CCACHE=y" >> .config
        echo "CONFIG_BUILD_LOG=y" >> .config
        echo "CONFIG_SIGNED_PACKAGES=n" >> .config
        echo "CONFIG_STRIP_KERNEL_EXPORTS=y" >> .config

    - name: Build Toolchain
      timeout-minutes: 30
      run: |
        make defconfig
        make tools/compile -j$(nproc) V=sc
        make toolchain/compile -j$(nproc) V=sc

    - name: Update Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Verify Package
      run: |
        if [ -f "package/kmod-rkp-ipid/Makefile" ]; then echo "Makefile exists"; else echo "Makefile missing"; exit 1; fi
        echo "CONFIG_PACKAGE_kmod-rkp-ipid=y" >> .config
        make defconfig

    - name: Compile kmod-rkp-ipid
      run: |
        make package/kmod-rkp-ipid/clean 2>/dev/null || true
        make package/kmod-rkp-ipid/compile -j$(nproc) V=s

    - name: Find IPK File
      run: |
        IPK_FILE=$(find ./bin -name "*kmod-rkp-ipid*.ipk" -type f | head -1)
        if [ -n "$IPK_FILE" ]; then
          echo "Found IPK: $IPK_FILE"
          cp "$IPK_FILE" ./kmod-rkp-ipid.ipk
          ls -lh kmod-rkp-ipid.ipk
        else
          echo "IPK not found, searching all IPK files:"
          find ./bin -name "*.ipk" -type f | head -10
          exit 1
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kmod-rkp-ipid-package
        path: ./kmod-rkp-ipid.ipk
        retention-days: 30
